name: Monthly Paper Crawler

on:
  schedule:
    - cron: "0 0 1 * *" # Run at 00:00 on the first day of every month
  workflow_dispatch: # Allow manual trigger
  push:
    branches:
      - main
      - master
    paths-ignore:
      - "README.md"
      - "papers_data.json"
      - "paper_details.json"
      - "strategy_reviews.json"
      - "library.json"

jobs:
  check_commit_message:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    outputs:
      should_run: ${{ steps.check_message.outputs.should_run }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - id: check_message
        run: |
          COMMIT_MSG=$(git log -1 --pretty=format:%s)
          if [[ "$COMMIT_MSG" == *"force update"* ]]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi

  crawl:
    runs-on: ubuntu-latest
    needs: [check_commit_message]
    if: github.event_name != 'push' || needs.check_commit_message.outputs.should_run == 'true'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file with secrets
        run: |
          echo "DEEPSEEK_OFFICIAL_API_KEY=${{ secrets.DEEPSEEK_OFFICIAL_API_KEY }}" > .env
          echo "SILICONFLOW_APIKEY=${{ secrets.SILICONFLOW_APIKEY }}" >> .env

      - name: Run crawler
        run: python get_abstracts.py

      - name: Run updater
        run: python paper_details_updater.py

      - name: Run reviewer
        run: python review_strategy_paper.py
        env:
          DEEPSEEK_OFFICIAL_API_KEY: ${{ secrets.DEEPSEEK_OFFICIAL_API_KEY }}
          SILICONFLOW_APIKEY: ${{ secrets.SILICONFLOW_APIKEY }}

      - name: Run generator
        run: python generate_library.py

      - name: Commit and push if changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add papers_data.json paper_details.json strategy_reviews.json library.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update papers data [skip ci]" && git push)
