name: Monthly Paper Crawler

on:
  schedule:
    - cron: "0 0 1 * *" # Run at 00:00 on the first day of every month
  workflow_dispatch: # Allow manual trigger

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run crawler
        run: python crawler.py

      - name: Run updater
        run: python paper_details_updater.py

      - name: Commit and push if changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add papers_data.json
          git add paper_details.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update papers data [skip ci]" && git push)
